title = "ゴミ溜め場"
description = "毎年申年ィ"
base_url = "https://blog.ivtune.net"
compile_sass = true
highlight_code = true
build_search_index = false
generate_rss = true
highlight_theme = "base16-ocean-light"

default_language = "en"

taxonomies = [
    {name = "tags"},
]

# theme
theme = "anatole-zola"

[languages.en.translations]
about = "About"
home = "Home"
tags = "Tags"
archive = "Archive"
links = "Links"
date_format = "%Y-%m-%d"
next_page = "Next Page"
last_page = "Last Page"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
# highlight_code = true

[extra]
# Put all your custom variables here

